import { init } from '../serverless.js';

export const handler = init({
	appDir: "_app",
	assets: new Set([".DS_Store","favicon/browserconfig.xml","favicon/favicon-114.png","favicon/favicon-120.png","favicon/favicon-144.png","favicon/favicon-150.png","favicon/favicon-152.png","favicon/favicon-16.png","favicon/favicon-160.png","favicon/favicon-180.png","favicon/favicon-192.png","favicon/favicon-310.png","favicon/favicon-32.png","favicon/favicon-57.png","favicon/favicon-60.png","favicon/favicon-64.png","favicon/favicon-70.png","favicon/favicon-72.png","favicon/favicon-76.png","favicon/favicon-96.png","favicon/favicon.ico","fonts/Friedrich-Book.eot","fonts/Friedrich-Book.woff","fonts/Friedrich-Book.woff2","fonts/SMHauser-60.woff","fonts/SMHauser-60.woff2","icons/.DS_Store","icons/svg/discord.svg","icons/svg/facebook.svg","icons/svg/github.svg","icons/svg/instagram.svg","icons/svg/twitter.svg","images/.DS_Store","images/events/.DS_Store","images/events/living-algorithms.jpg","images/events/moving-strings/adam.jpg","images/events/moving-strings/chris.jpg","images/events/moving-strings/mrp_andrew.jpg","images/events/moving-strings/mrp_concert.jpg","images/events/moving-strings/mrp_workshops.jpg","images/events/moving-strings/tabita.jpg","images/logos/rannis.png","images/logos/rannis.svg","images/news/.DS_Store","images/news/aaabcn.png","images/news/bela.png","images/news/karl.jpeg","images/news/phd2advert.jpeg","images/news/robin_device.jpeg","images/news/rusl-sigga.png","images/news/ruslbanner.jpeg","images/news/sigga-4884.jpg","images/news/soundwork.png","images/news/steve.jpg","images/news/synthabaeli.jpg","images/news/trash-group.jpg","images/news/trash-stuff1.jpg","images/news/trash-stuff2.jpg","images/news/trash_schedule.png","images/openlabs/ol4a.jpeg","images/openlabs/ol6a.JPG","images/openlabs/ol6b.JPG","images/openlabs/ol6c.JPG","images/people/davidbrynjar.JPG","images/people/davidbrynjar.png","images/people/enrike_1500.jpg","images/people/esther.jpg","images/people/ezra.jpeg","images/people/halldor.jpg","images/people/jack.jpg","images/people/jonr.jpg","images/people/karl.png","images/people/kit.jpg","images/people/marco_1500.jpg","images/people/robin.jpg","images/people/sean.png","images/people/sigga.jpg","images/people/steve_1500.jpg","images/people/thor.jpg","images/people/victor.jpg","images/research/projects/halldorophone.jpg","images/research/projects/protolangspil.jpg","images/research/projects/protolangspil2.jpg","images/research/projects/stenophone.jpg","images/research/projects/supercollider.png","images/research/projects/threnoscope.png","images/stock/empty_lab_yellow.jpg","images/stock/frettabladid21.jpg","images/stock/halldor_kastljos.png","images/stock/halldorophone.jpeg","images/stock/halldorophone3.jpg","images/stock/hlci_sq_1.jpg","images/stock/hlci_sq_2.jpg","images/stock/hugarflug.png","images/stock/lestin2020.png","images/stock/openlab_5_roundtable.jpeg","images/stock/phd2advert.jpeg","images/stock/prototype_langspil_cardboard.jpg","images/stock/prototype_langspil_plywood_1.jpg","images/stock/prototype_langspil_plywood_2_electrical_chords.jpg","images/stock/schermata1.png","images/stock/schermata2.png","images/stock/student_IIL.jpeg","images/stock/thraedir.png","manifest.json","publications.bib","seo/ogimage.jpg","vid/moving_strings.mp4"]),
	mimeTypes: {".xml":"application/xml",".png":"image/png",".ico":"image/vnd.microsoft.icon",".eot":"application/vnd.ms-fontobject",".woff":"font/woff",".woff2":"font/woff2",".svg":"image/svg+xml",".jpg":"image/jpeg",".jpeg":"image/jpeg",".JPG":"image/jpeg",".json":"application/json",".mp4":"video/mp4"},
	_: {
		entry: {"file":"_app/immutable/start-3d2c4441.js","imports":["_app/immutable/start-3d2c4441.js","_app/immutable/chunks/index-889f64f7.js","_app/immutable/chunks/index-a67f61ca.js"],"stylesheets":[]},
		nodes: [
			() => import('../server/nodes/0.js'),
			() => import('../server/nodes/1.js'),
			() => import('../server/nodes/5.js'),
			() => import('../server/nodes/2.js'),
			() => import('../server/nodes/3.js'),
			() => import('../server/nodes/12.js'),
			() => import('../server/nodes/50.js'),
			() => import('../server/nodes/51.js'),
			() => import('../server/nodes/57.js'),
			() => import('../server/nodes/70.js'),
			() => import('../server/nodes/4.js'),
			() => import('../server/nodes/6.js'),
			() => import('../server/nodes/7.js'),
			() => import('../server/nodes/8.js'),
			() => import('../server/nodes/9.js'),
			() => import('../server/nodes/10.js'),
			() => import('../server/nodes/11.js'),
			() => import('../server/nodes/13.js'),
			() => import('../server/nodes/14.js'),
			() => import('../server/nodes/15.js'),
			() => import('../server/nodes/16.js'),
			() => import('../server/nodes/17.js'),
			() => import('../server/nodes/18.js'),
			() => import('../server/nodes/19.js'),
			() => import('../server/nodes/20.js'),
			() => import('../server/nodes/21.js'),
			() => import('../server/nodes/22.js'),
			() => import('../server/nodes/23.js'),
			() => import('../server/nodes/24.js'),
			() => import('../server/nodes/25.js'),
			() => import('../server/nodes/26.js'),
			() => import('../server/nodes/27.js'),
			() => import('../server/nodes/28.js'),
			() => import('../server/nodes/29.js'),
			() => import('../server/nodes/30.js'),
			() => import('../server/nodes/31.js'),
			() => import('../server/nodes/32.js'),
			() => import('../server/nodes/33.js'),
			() => import('../server/nodes/34.js'),
			() => import('../server/nodes/35.js'),
			() => import('../server/nodes/36.js'),
			() => import('../server/nodes/37.js'),
			() => import('../server/nodes/38.js'),
			() => import('../server/nodes/39.js'),
			() => import('../server/nodes/40.js'),
			() => import('../server/nodes/41.js'),
			() => import('../server/nodes/42.js'),
			() => import('../server/nodes/43.js'),
			() => import('../server/nodes/44.js'),
			() => import('../server/nodes/45.js'),
			() => import('../server/nodes/46.js'),
			() => import('../server/nodes/47.js'),
			() => import('../server/nodes/48.js'),
			() => import('../server/nodes/49.js'),
			() => import('../server/nodes/52.js'),
			() => import('../server/nodes/53.js'),
			() => import('../server/nodes/54.js'),
			() => import('../server/nodes/55.js'),
			() => import('../server/nodes/56.js'),
			() => import('../server/nodes/58.js'),
			() => import('../server/nodes/59.js'),
			() => import('../server/nodes/60.js'),
			() => import('../server/nodes/61.js'),
			() => import('../server/nodes/62.js'),
			() => import('../server/nodes/63.js'),
			() => import('../server/nodes/64.js'),
			() => import('../server/nodes/65.js'),
			() => import('../server/nodes/66.js'),
			() => import('../server/nodes/67.js'),
			() => import('../server/nodes/68.js'),
			() => import('../server/nodes/69.js'),
			() => import('../server/nodes/71.js'),
			() => import('../server/nodes/72.js'),
			() => import('../server/nodes/73.js'),
			() => import('../server/nodes/74.js')
		],
		routes: [
			{
				type: 'page',
				id: "",
				pattern: /^\/$/,
				names: [],
				types: [],
				path: "/",
				shadow: null,
				a: [0,2],
				b: [1]
			},
			{
				type: 'page',
				id: "about",
				pattern: /^\/about\/?$/,
				names: [],
				types: [],
				path: "/about",
				shadow: null,
				a: [0,3],
				b: [1]
			},
			{
				type: 'page',
				id: "collaborate",
				pattern: /^\/collaborate\/?$/,
				names: [],
				types: [],
				path: "/collaborate",
				shadow: null,
				a: [0,4],
				b: [1]
			},
			{
				type: 'page',
				id: "news",
				pattern: /^\/news\/?$/,
				names: [],
				types: [],
				path: "/news",
				shadow: null,
				a: [0,5],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab",
				pattern: /^\/openlab\/?$/,
				names: [],
				types: [],
				path: "/openlab",
				shadow: null,
				a: [0,6],
				b: [1]
			},
			{
				type: 'page',
				id: "outputs",
				pattern: /^\/outputs\/?$/,
				names: [],
				types: [],
				path: "/outputs",
				shadow: null,
				a: [0,7],
				b: [1]
			},
			{
				type: 'page',
				id: "people",
				pattern: /^\/people\/?$/,
				names: [],
				types: [],
				path: "/people",
				shadow: null,
				a: [0,8],
				b: [1]
			},
			{
				type: 'page',
				id: "research",
				pattern: /^\/research\/?$/,
				names: [],
				types: [],
				path: "/research",
				shadow: null,
				a: [0,9],
				b: [1]
			},
			{
				type: 'endpoint',
				id: "research/projects.json",
				pattern: /^\/research\/projects\.json$/,
				names: [],
				types: [],
				load: () => import('../server/entries/endpoints/research/projects.json.js')
			},
			{
				type: 'endpoint',
				id: "people/people.json",
				pattern: /^\/people\/people\.json$/,
				names: [],
				types: [],
				load: () => import('../server/entries/endpoints/people/people.json.js')
			},
			{
				type: 'endpoint',
				id: "openlab/openlabs.json",
				pattern: /^\/openlab\/openlabs\.json$/,
				names: [],
				types: [],
				load: () => import('../server/entries/endpoints/openlab/openlabs.json.js')
			},
			{
				type: 'endpoint',
				id: "news/items.json",
				pattern: /^\/news\/items\.json$/,
				names: [],
				types: [],
				load: () => import('../server/entries/endpoints/news/items.json.js')
			},
			{
				type: 'page',
				id: "events/moving-strings",
				pattern: /^\/events\/moving-strings\/?$/,
				names: [],
				types: [],
				path: "/events/moving-strings",
				shadow: null,
				a: [0,10],
				b: [1]
			},
			{
				type: 'page',
				id: "news/ICLC2021",
				pattern: /^\/news\/ICLC2021\/?$/,
				names: [],
				types: [],
				path: "/news/ICLC2021",
				shadow: null,
				a: [0,11],
				b: [1]
			},
			{
				type: 'page',
				id: "news/good-start",
				pattern: /^\/news\/good-start\/?$/,
				names: [],
				types: [],
				path: "/news/good-start",
				shadow: null,
				a: [0,12],
				b: [1]
			},
			{
				type: 'page',
				id: "news/google-summer-of-code",
				pattern: /^\/news\/google-summer-of-code\/?$/,
				names: [],
				types: [],
				path: "/news/google-summer-of-code",
				shadow: null,
				a: [0,13],
				b: [1]
			},
			{
				type: 'page',
				id: "news/gsoc2022",
				pattern: /^\/news\/gsoc2022\/?$/,
				names: [],
				types: [],
				path: "/news/gsoc2022",
				shadow: null,
				a: [0,14],
				b: [1]
			},
			{
				type: 'page',
				id: "news/halldorophone-kastljos",
				pattern: /^\/news\/halldorophone-kastljos\/?$/,
				names: [],
				types: [],
				path: "/news/halldorophone-kastljos",
				shadow: null,
				a: [0,15],
				b: [1]
			},
			{
				type: 'page',
				id: "news/icelandic-news",
				pattern: /^\/news\/icelandic-news\/?$/,
				names: [],
				types: [],
				path: "/news/icelandic-news",
				shadow: null,
				a: [0,16],
				b: [1]
			},
			{
				type: 'page',
				id: "news/karl",
				pattern: /^\/news\/karl\/?$/,
				names: [],
				types: [],
				path: "/news/karl",
				shadow: null,
				a: [0,17],
				b: [1]
			},
			{
				type: 'page',
				id: "news/living-algorithms",
				pattern: /^\/news\/living-algorithms\/?$/,
				names: [],
				types: [],
				path: "/news/living-algorithms",
				shadow: null,
				a: [0,18],
				b: [1]
			},
			{
				type: 'page',
				id: "news/moving-strings",
				pattern: /^\/news\/moving-strings\/?$/,
				names: [],
				types: [],
				path: "/news/moving-strings",
				shadow: null,
				a: [0,19],
				b: [1]
			},
			{
				type: 'page',
				id: "news/nime-2022-workshop",
				pattern: /^\/news\/nime-2022-workshop\/?$/,
				names: [],
				types: [],
				path: "/news/nime-2022-workshop",
				shadow: null,
				a: [0,20],
				b: [1]
			},
			{
				type: 'page',
				id: "news/nordic-popular-music-union",
				pattern: /^\/news\/nordic-popular-music-union\/?$/,
				names: [],
				types: [],
				path: "/news/nordic-popular-music-union",
				shadow: null,
				a: [0,21],
				b: [1]
			},
			{
				type: 'page',
				id: "news/on-the-fly-residency",
				pattern: /^\/news\/on-the-fly-residency\/?$/,
				names: [],
				types: [],
				path: "/news/on-the-fly-residency",
				shadow: null,
				a: [0,22],
				b: [1]
			},
			{
				type: 'page',
				id: "news/phd2-deadline",
				pattern: /^\/news\/phd2-deadline\/?$/,
				names: [],
				types: [],
				path: "/news/phd2-deadline",
				shadow: null,
				a: [0,23],
				b: [1]
			},
			{
				type: 'page',
				id: "news/phd2",
				pattern: /^\/news\/phd2\/?$/,
				names: [],
				types: [],
				path: "/news/phd2",
				shadow: null,
				a: [0,24],
				b: [1]
			},
			{
				type: 'page',
				id: "news/robin",
				pattern: /^\/news\/robin\/?$/,
				names: [],
				types: [],
				path: "/news/robin",
				shadow: null,
				a: [0,25],
				b: [1]
			},
			{
				type: 'page',
				id: "news/root-workshop-2022",
				pattern: /^\/news\/root-workshop-2022\/?$/,
				names: [],
				types: [],
				path: "/news/root-workshop-2022",
				shadow: null,
				a: [0,26],
				b: [1]
			},
			{
				type: 'page',
				id: "news/rusl2022",
				pattern: /^\/news\/rusl2022\/?$/,
				names: [],
				types: [],
				path: "/news/rusl2022",
				shadow: null,
				a: [0,27],
				b: [1]
			},
			{
				type: 'page',
				id: "news/soundworks",
				pattern: /^\/news\/soundworks\/?$/,
				names: [],
				types: [],
				path: "/news/soundworks",
				shadow: null,
				a: [0,28],
				b: [1]
			},
			{
				type: 'page',
				id: "news/steve-residency",
				pattern: /^\/news\/steve-residency\/?$/,
				names: [],
				types: [],
				path: "/news/steve-residency",
				shadow: null,
				a: [0,29],
				b: [1]
			},
			{
				type: 'page',
				id: "news/summer-interns",
				pattern: /^\/news\/summer-interns\/?$/,
				names: [],
				types: [],
				path: "/news/summer-interns",
				shadow: null,
				a: [0,30],
				b: [1]
			},
			{
				type: 'page',
				id: "news/synthabaeli",
				pattern: /^\/news\/synthabaeli\/?$/,
				names: [],
				types: [],
				path: "/news/synthabaeli",
				shadow: null,
				a: [0,31],
				b: [1]
			},
			{
				type: 'page',
				id: "news/trash-workshop",
				pattern: /^\/news\/trash-workshop\/?$/,
				names: [],
				types: [],
				path: "/news/trash-workshop",
				shadow: null,
				a: [0,32],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/1",
				pattern: /^\/openlab\/1\/?$/,
				names: [],
				types: [],
				path: "/openlab/1",
				shadow: null,
				a: [0,33],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/10",
				pattern: /^\/openlab\/10\/?$/,
				names: [],
				types: [],
				path: "/openlab/10",
				shadow: null,
				a: [0,34],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/11",
				pattern: /^\/openlab\/11\/?$/,
				names: [],
				types: [],
				path: "/openlab/11",
				shadow: null,
				a: [0,35],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/12",
				pattern: /^\/openlab\/12\/?$/,
				names: [],
				types: [],
				path: "/openlab/12",
				shadow: null,
				a: [0,36],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/13",
				pattern: /^\/openlab\/13\/?$/,
				names: [],
				types: [],
				path: "/openlab/13",
				shadow: null,
				a: [0,37],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/14",
				pattern: /^\/openlab\/14\/?$/,
				names: [],
				types: [],
				path: "/openlab/14",
				shadow: null,
				a: [0,38],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/15",
				pattern: /^\/openlab\/15\/?$/,
				names: [],
				types: [],
				path: "/openlab/15",
				shadow: null,
				a: [0,39],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/16",
				pattern: /^\/openlab\/16\/?$/,
				names: [],
				types: [],
				path: "/openlab/16",
				shadow: null,
				a: [0,40],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/17",
				pattern: /^\/openlab\/17\/?$/,
				names: [],
				types: [],
				path: "/openlab/17",
				shadow: null,
				a: [0,41],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/18",
				pattern: /^\/openlab\/18\/?$/,
				names: [],
				types: [],
				path: "/openlab/18",
				shadow: null,
				a: [0,42],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/19",
				pattern: /^\/openlab\/19\/?$/,
				names: [],
				types: [],
				path: "/openlab/19",
				shadow: null,
				a: [0,43],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/2",
				pattern: /^\/openlab\/2\/?$/,
				names: [],
				types: [],
				path: "/openlab/2",
				shadow: null,
				a: [0,44],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/20",
				pattern: /^\/openlab\/20\/?$/,
				names: [],
				types: [],
				path: "/openlab/20",
				shadow: null,
				a: [0,45],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/21",
				pattern: /^\/openlab\/21\/?$/,
				names: [],
				types: [],
				path: "/openlab/21",
				shadow: null,
				a: [0,46],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/3",
				pattern: /^\/openlab\/3\/?$/,
				names: [],
				types: [],
				path: "/openlab/3",
				shadow: null,
				a: [0,47],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/4",
				pattern: /^\/openlab\/4\/?$/,
				names: [],
				types: [],
				path: "/openlab/4",
				shadow: null,
				a: [0,48],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/5",
				pattern: /^\/openlab\/5\/?$/,
				names: [],
				types: [],
				path: "/openlab/5",
				shadow: null,
				a: [0,49],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/6",
				pattern: /^\/openlab\/6\/?$/,
				names: [],
				types: [],
				path: "/openlab/6",
				shadow: null,
				a: [0,50],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/7",
				pattern: /^\/openlab\/7\/?$/,
				names: [],
				types: [],
				path: "/openlab/7",
				shadow: null,
				a: [0,51],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/8",
				pattern: /^\/openlab\/8\/?$/,
				names: [],
				types: [],
				path: "/openlab/8",
				shadow: null,
				a: [0,52],
				b: [1]
			},
			{
				type: 'page',
				id: "openlab/9",
				pattern: /^\/openlab\/9\/?$/,
				names: [],
				types: [],
				path: "/openlab/9",
				shadow: null,
				a: [0,53],
				b: [1]
			},
			{
				type: 'page',
				id: "people/davidbrynjar",
				pattern: /^\/people\/davidbrynjar\/?$/,
				names: [],
				types: [],
				path: "/people/davidbrynjar",
				shadow: null,
				a: [0,54],
				b: [1]
			},
			{
				type: 'page',
				id: "people/enrike",
				pattern: /^\/people\/enrike\/?$/,
				names: [],
				types: [],
				path: "/people/enrike",
				shadow: null,
				a: [0,55],
				b: [1]
			},
			{
				type: 'page',
				id: "people/esther",
				pattern: /^\/people\/esther\/?$/,
				names: [],
				types: [],
				path: "/people/esther",
				shadow: null,
				a: [0,56],
				b: [1]
			},
			{
				type: 'page',
				id: "people/ezra",
				pattern: /^\/people\/ezra\/?$/,
				names: [],
				types: [],
				path: "/people/ezra",
				shadow: null,
				a: [0,57],
				b: [1]
			},
			{
				type: 'page',
				id: "people/halldor",
				pattern: /^\/people\/halldor\/?$/,
				names: [],
				types: [],
				path: "/people/halldor",
				shadow: null,
				a: [0,58],
				b: [1]
			},
			{
				type: 'page',
				id: "people/jack",
				pattern: /^\/people\/jack\/?$/,
				names: [],
				types: [],
				path: "/people/jack",
				shadow: null,
				a: [0,59],
				b: [1]
			},
			{
				type: 'page',
				id: "people/jon",
				pattern: /^\/people\/jon\/?$/,
				names: [],
				types: [],
				path: "/people/jon",
				shadow: null,
				a: [0,60],
				b: [1]
			},
			{
				type: 'page',
				id: "people/karl",
				pattern: /^\/people\/karl\/?$/,
				names: [],
				types: [],
				path: "/people/karl",
				shadow: null,
				a: [0,61],
				b: [1]
			},
			{
				type: 'page',
				id: "people/kit",
				pattern: /^\/people\/kit\/?$/,
				names: [],
				types: [],
				path: "/people/kit",
				shadow: null,
				a: [0,62],
				b: [1]
			},
			{
				type: 'page',
				id: "people/marco",
				pattern: /^\/people\/marco\/?$/,
				names: [],
				types: [],
				path: "/people/marco",
				shadow: null,
				a: [0,63],
				b: [1]
			},
			{
				type: 'page',
				id: "people/robin",
				pattern: /^\/people\/robin\/?$/,
				names: [],
				types: [],
				path: "/people/robin",
				shadow: null,
				a: [0,64],
				b: [1]
			},
			{
				type: 'page',
				id: "people/sean",
				pattern: /^\/people\/sean\/?$/,
				names: [],
				types: [],
				path: "/people/sean",
				shadow: null,
				a: [0,65],
				b: [1]
			},
			{
				type: 'page',
				id: "people/sigga",
				pattern: /^\/people\/sigga\/?$/,
				names: [],
				types: [],
				path: "/people/sigga",
				shadow: null,
				a: [0,66],
				b: [1]
			},
			{
				type: 'page',
				id: "people/steve",
				pattern: /^\/people\/steve\/?$/,
				names: [],
				types: [],
				path: "/people/steve",
				shadow: null,
				a: [0,67],
				b: [1]
			},
			{
				type: 'page',
				id: "people/thor",
				pattern: /^\/people\/thor\/?$/,
				names: [],
				types: [],
				path: "/people/thor",
				shadow: null,
				a: [0,68],
				b: [1]
			},
			{
				type: 'page',
				id: "people/victor",
				pattern: /^\/people\/victor\/?$/,
				names: [],
				types: [],
				path: "/people/victor",
				shadow: null,
				a: [0,69],
				b: [1]
			},
			{
				type: 'page',
				id: "research/halldorophone",
				pattern: /^\/research\/halldorophone\/?$/,
				names: [],
				types: [],
				path: "/research/halldorophone",
				shadow: null,
				a: [0,70],
				b: [1]
			},
			{
				type: 'page',
				id: "research/langspil",
				pattern: /^\/research\/langspil\/?$/,
				names: [],
				types: [],
				path: "/research/langspil",
				shadow: null,
				a: [0,71],
				b: [1]
			},
			{
				type: 'page',
				id: "research/livinglooper",
				pattern: /^\/research\/livinglooper\/?$/,
				names: [],
				types: [],
				path: "/research/livinglooper",
				shadow: null,
				a: [0,72],
				b: [1]
			},
			{
				type: 'page',
				id: "research/stenophone",
				pattern: /^\/research\/stenophone\/?$/,
				names: [],
				types: [],
				path: "/research/stenophone",
				shadow: null,
				a: [0,73],
				b: [1]
			},
			{
				type: 'page',
				id: "research/threnoscope",
				pattern: /^\/research\/threnoscope\/?$/,
				names: [],
				types: [],
				path: "/research/threnoscope",
				shadow: null,
				a: [0,74],
				b: [1]
			}
		],
		matchers: async () => {
			
			return {  };
		}
	}
});
